
(define-module (xmlreader)
  :export (xml/make-reader-from-file
           xml/make-reader-from-string
           xml/read
           xml/read-inner-xml
           xml/read-outer-xml
           xml/read-string
           xml/read-attribute-value
           xml/get-attribute-count
           xml/get-base-uri
           xml/get-depth
           xml/has-attributes
           xml/has-value
           xml/is-default
           xml/is-empty-element
           xml/get-local-name
           xml/get-name
           xml/get-namespace-uri
           xml/get-node-type
           xml/get-prefix
           xml/get-quote-char
           xml/get-value
           xml/get-xml-lang
           xml/get-read-state
           xml/close
           xml/get-attribute
           xml/lookup-namespace
           xml/move-to-attribute
           xml/move-to-first-attribute
           xml/move-to-next-attribute
           xml/move-to-element
           xml/get-normalization
           xml/get-parser-property
           xml/set-parser-property
           xml/get-current-node
           xml/expand
           xml/next
           xml/is-valid

           xmlNodeType.Attribute
           xmlNodeType.CDATA
           xmlNodeType.Comment
           xmlNodeType.Document
           xmlNodeType.DocumentFragment
           xmlNodeType.DocumentType
           xmlNodeType.Element
           xmlNodeType.EndElement
           xmlNodeType.EndEntity
           xmlNodeType.Entity
           xmlNodeType.EntityReference
           xmlNodeType.None
           xmlNodeType.Notation
           xmlNodeType.ProcessingInstruction
           xmlNodeType.SignificantWhitespace
           xmlNodeType.Text
           xmlNodeType.Whitespace
           xmlNodeType.XmlDeclaration
           xmlReadState.Closed
           xmlReadState.EndOfFile
           xmlReadState.Error
           xmlReadState.Initial
           xmlReadState.Interactive
           xmlReadState.Reading
           ParserProperties.LoadDtd
           ParserProperties.DefaultAttrs
           ParserProperties.Validate
           ParserProperties.SubstEntities))

(load-extension "libguile-xmlreader" "init_xmlreader")
